### ISSUE TITLE
What is the license and copyright of the source code?

### ISSUE THREAD

**Issue by jeremiah** [GXimingLu/neurologic_decoding#12]
Hi,

What is the license and copyright of python and shell script source code you distribute? This is pertinent since various organizations won't be able to use or contribute to the project if the license or copyright is unclear. Also, you appear to be using algorithms and/or source code from Facebook (Meta) which is copyright Facebook; 

>  Copyright (c) 2019-present, Facebook, Inc.
>  All rights reserved.
> 
>  This source code is licensed under the license found in the
>  LICENSE file in the root directory of this source tree.
> 

(This text is found in the source code file of the URL you paste in your source code: https://github.com/facebookresearch/XLM/blob/9e6f6814d17be4fe5b15f2e6c43eb2b2d76daeb4/src/model/transformer.py#L529)

**Comment by GloriaXimingLu** [comment]
Hi, thanks for the reminder! We've added the Apache-2.0 license in our repo!
