### ISSUE TITLE
How do you introduce negative lexical constraints?

### ISSUE THREAD

**Issue by t-zetsu** [GXimingLu/neurologic_decoding#2]
Thanks for neurologic decoding!
I'd like to do some experiments with your neurologic decoding, but I'm having trouble figuring out how to introduce negative lexical constraints.
Positive lexical constraints are given in the following form, 
`[["drill", "drills"], ["fields", "field"], ["run", "running", "runs"], ["team", "teams"]]`
but what form are negative constraints given in?

**Comment by MHDBST** [comment]
Hi,
I'm trying to run the code over my predefined constraints; it works well when all the constraints are positive. But I didn't see any example of negative constraints.

When I looked into the code, I found that the function `utils_seq2seq.tokenize_constraints` always returns `True` in the `tokenize` method, and this label is later used to distinguish between positive and negative constraints in `lexical_constraints.init_batch` when the class `ConstrainedHypothesis` is initiated.

Have you considered defining negative constraints? How are they being handled? Should I use any specific lexical or symbolic characters to define negative constraints?

**Comment by GloriaXimingLu** [comment]
Hi, thanks for checking in!
I've added the code and constraint file for the [constrained MT task](https://github.com/GXimingLu/neurologic_decoding/tree/main/mt), where both negative and positive constraints are used. Specifically, you can find the implementation to enforce negative constraints [here](https://github.com/GXimingLu/neurologic_decoding/blob/6694be96188e2abd8a712b5aa900a966024f206c/mt/generate.py#L494-L504).
