### ISSUE TITLE
Interested in your NAACL22 paper

### ISSUE THREAD

**Issue by zhenduow** [GXimingLu/neurologic_decoding#6]
Hello Ximing,

I am interested in your NAACL22 paper about _Neurologic a*esque decoding_.  Do you have plans to publish your code any time soon? Thank you very much!

**Comment by GloriaXimingLu** [comment]
Hi, thanks for your interest! We've open source our A* neurologic code [here](https://github.com/GXimingLu/a_star_neurologic).
