### ISSUE TITLE
Question regarding usage of generate when input_embeds is present

### ISSUE THREAD

**Issue by soumyasanyal** [GXimingLu/neurologic_decoding#8]
Thanks for sharing the code! We have been trying to integrate this into our project. One challenge we find is that our use-case needs us to pass some `input_embeds` to the generate function, instead of `input_ids`. Is there a plan to support that in the code-base or can you help us in understanding the necessary files that need to be changed to support `inputs_embeds` as an input option?

For reference, the Huggingface [generate function](https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin) has `inputs` that can be both ids and embeddings.

Thanks in advance!

**Comment by chansonzhang** [comment]
I found a description in Huggingface's generation function [parameter desciption](https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate.inputs).
> For decoder-only models inputs should of in the format of input_ids.

I guess perhaps the neurologic_decoding is a decoder-only model so the inputs can only be input_ids.

**Comment by GloriaXimingLu** [comment]
Hi, thanks for the question! Our [code](https://github.com/GXimingLu/neurologic_decoding/blob/0d387c904ea0ce0f322f6bd1ceb024f512359b30/lm/generate.py#L15) is an extension of generation function in huggingface, so we automatically support all their parameters. You could pass in `input_embeds` in our [generate](https://github.com/GXimingLu/neurologic_decoding/blob/0d387c904ea0ce0f322f6bd1ceb024f512359b30/lm/decode.py#L110) function in the same way as using `model.generate` function in huggingface.
